const lang = {
  eng: {
    home: "Home",
    contacts: "Contacts",
    manageContacts: "Manage contacts",
    devices: "Devices",
    manageDevices: "Manage devices",
    tasks: "Tasks",
    manageTasks: "Manage tasks",
    support: "Support",
    admin: "Admin",
    requestSupport: "Request support",
    toggleSidebar: "Toggle sidebar",
    filter: "Filter",
    personal: "Personal",
    company: "Company",
    all: "All",
    addContact: "Add contact",
    addDevice: "Add device",
    loading: "Loading",
    noData: "No data",
    charts: "Charts",
    contact: "Contact",
    category: "Category",
    name: "Name",
    eMail: "E-Mail",
    telephone: "Telephone",
    role: "Role",
    comments: "Comments",
    edit: "Edit",
    delete: "Delete",
    editContact: "Edit contact",
    editDevice: "Edit device",
    deleteContact: "Delete contact",
    deleteDevice: "Delete device",
    cancel: "Cancel",
    confirm: "Confirm",
    contactExists: "Contact already exists",
    deviceExists: "Device already exists",
    send: "Send",
    required: "Required",
    completed: "Completed",
    pending: "Pending",
    status: "Status",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    device: "Device",
    task: "Task",
    ticket: "Ticket",
    type: "Type",
    model: "Model",
    serialNumber: "Serial number",
    notFound: "Not found",
    resourceNotFound: "Resource not found",
    goHome: "Go home",
    profile: "Profile",
    signOut: "Sign out",
    signIn: "Sign in",
    youMust: "You must",
    toAccessThisSection: "To access this section",
    user: "User"

  },
  esp: {
    home: "Inicio",
    contacts: "Contactos",
    manageContacts: "Gestionar contactos",
    devices: "Dispositivos",
    manageDevices: "Gestionar dispositivos",
    tasks: "Tareas",
    manageTasks: "Gestionar tareas",
    support: "Soporte",
    admin: "Admin",
    requestSupport: "Solicitar soporte",
    toggleSidebar: "Alternar barra lateral",
    filter: "Filtrar",
    personal: "Personal",
    company: "Compañía",
    all: "Todos",
    addContact: "Añadir contacto",
    addDevice: "Añadir dispositivo",
    loading: "Cargando",
    noData: "Sin datos",
    charts: "Gráficos",
    contact: "Contacto",
    category: "Categoría",
    name: "Nombre",
    eMail: "Correo electrónico",
    telephone: "Teléfono",
    role: "Rol",
    comments: "Comentarios",
    edit: "Editar",
    delete: "Eliminar",
    editContact: "Editar contacto",
    editDevice: "Editar dispositivo",
    deleteContact: "Eliminar contacto",
    deleteDevice: "Eliminar dispositivo",
    cancel: "Cancelar",
    confirm: "Confirmar",
    contactExists: "El contacto ya existe",
    deviceExists: "El dispositivo ya existe",
    send: "Enviar",
    required: "Requerido",
    completed: "Completado",
    pending: "Pendiente",
    status: "Estado",
    priority: "Prioridad",
    low: "Baja",
    medium: "Media",
    high: "Alta",
    device: "Dispositivo",
    task: "Tarea",
    ticket: "Ticket",
    type: "Tipo",
    model: "Modelo",
    serialNumber: "Número de serie",
    notFound: "No encontrado",
    resourceNotFound: "Recurso no encontrado",
    goHome: "Ir al inicio",
    profile: "Perfil",
    signOut: "Cerrar sesión",
    signIn: "Iniciar sesión",
    youMust: "Debes",
    toAccessThisSection: "Para acceder a esta sección",
    user: "Usuario"

  }
}

export default lang